### ISSUE TITLE
Crash in initialHeaderAdapter

### ISSUE THREAD

**Issue by bottiger** [bottiger/SoundWaves#28]
STACK_TRACE=java.lang.NullPointerException
at org.bottiger.podcast.adapters.decoration.InitialHeaderAdapter.onBindViewHolder(InitialHeaderAdapter.java:45)
at org.bottiger.podcast.adapters.decoration.InitialHeaderAdapter.onBindViewHolder(InitialHeaderAdapter.java:20)
at com.eowise.recyclerview.stickyheaders.HeaderStore.getHeaderViewByItem(HeaderStore.java:45)

**Comment by bottiger** [comment]
Fixed in master branch. Will be included in 0.88
