### ISSUE TITLE
Inconsistency detected. Invalid view holder adapter 

### ISSUE THREAD

**Issue by bottiger** [bottiger/SoundWaves#40]
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{4344d348 position=1 id=10, oldPos=-1, pLpos:-1 scrap tmpDetached no parent}
at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:3229)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3359)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3340)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1810)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1306)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1988)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)

**Comment by bottiger** [comment]
Fixed in master branch

**Comment by jjhesk** [comment]
@bottiger how did you fix this issue?? I had the [same issue](https://github.com/cymcsg/UltimateRecyclerView/issues/135)

**Comment by bottiger** [comment]
@jjhesk I'm sorry. I do not remember

**Comment by Naderkunbhar** [comment]
Dear I have same issue ,App crash when I want to update adapter ,it crashes 
`private void filter(String query) {
        query = query.toLowerCase();
        final SparseArray<String> filteredModelList = new SparseArray<>();
        for (int position = 0; position < sStringList.length; position++) {
            if (sStringList[position].contains(query)) {
                filteredModelList.put(position, sStringList[position]);
            } else {
                ray.remove(position);
                adapter.notifyItemRemoved(position);
            }
        }
    }`
