### ISSUE TITLE
bindExandedPlayer  NullPointerException

### ISSUE THREAD

**Issue by bottiger** [bottiger/SoundWaves#51]
java.lang.NullPointerException
at org.bottiger.podcast.adapters.PlaylistAdapter.bindExandedPlayer(PlaylistAdapter.java:260)
at org.bottiger.podcast.adapters.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.java:174)
at org.bottiger.podcast.adapters.PlaylistAdapter.onBindViewHolder(PlaylistAdapter.java:47)
at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:4805)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4106)
at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:3999)
at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1892)
at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1338)
at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1301)
at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:534)
at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2411)
at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2709)
at android.view.View.layout(View.java:15204)
at android.view.ViewGroup.layout(ViewGroup.java:4793)
at android.widget.FrameLayout.onLayout(FrameLayout.java:448)

**Comment by bottiger** [comment]
Fixed in master
